---
gnome_dconf_settings:
  - key: "/org/gnome/desktop/wm/preferences/button-layout"
    value: "':minimize,maximize,close'"
  - key: "/org/gnome/desktop/input-sources/sources"
    value: "[('xkb', 'ch+fr')]"
  - key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Adwaita'"
  - key: "/org/gnome/desktop/interface/color-scheme"
    value: "'prefer-dark'"
  - key: "/org/gnome/desktop/screensaver/picture-uri"
    value: "'file:///usr/share/backgrounds/gnome/blobs-l.svg'"
  - key: "/org/gnome/desktop/interface/accent-color"
    value: "'orange'"
  - key: "/org/gnome/desktop/calendar/show-weekdate"
    value: "true"
  - key: "/org/gnome/shell/favorite-apps"
    value: "['firefox.desktop',
     'google-chrome.desktop',
     'org.gnome.Nautilus.desktop',
     'org.gnome.Console.desktop',
     'signal-desktop.desktop',
     'spotify-launcher.desktop',
     'bitwarden.desktop',
     'code.desktop']"
  - key: "/org/gnome/shell/keybindings/show-screenshot-ui"
    value: "['<Shift><Super>s']"
  - key: "/org/gnome/desktop/peripherals/keyboard/numlock-state"
    value: "true"
  - key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled"
    value: "true"
  - key: "/org/gnome/settings-daemon/plugins/color/night-light-schedule-from"
    value: "21.0"
  - key: "/org/gnome/settings-daemon/plugins/color/night-light-schedule-to"
    value: "6.0"
  - key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-timeout"
    value: "1800"
  - key: "/org/gnome/settings-daemon/plugins/power/ambient-enabled"
    value: "true"
  - key: "/org/gnome/settings-daemon/plugins/power/idle-brightness"
    value: "30"
  - key: "/org/gnome/settings-daemon/plugins/power/idle-dim"
    value: "true"
  - key: "/org/gnome/settings-daemon/plugins/power/power-button-action"
    value: "'suspend'"
  - key: "/org/gnome/settings-daemon/plugins/power/power-saver-profile-on-low-battery"
    value: "true"
  - key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type"
    value: "'suspend'"
  - key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-timeout"
    value: "900"
  - key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-type"
    value: "'suspend'"
