---
- name: Configure and install system
  hosts: localhost
  connection: local
  become: true

  vars:
    aur_user: "{{ lookup('env', 'USER') }}"

  roles:
    - base_packages
    - gnome
    - zsh
    - ssh_keygen
    - bluetooth
    - displaylink
    - git
    - docker
    - apps
    - browsers
