---
- hosts: localhost
  connection: local
  become: true

  vars:
    aur_user: christophe

  roles:
    - base_packages
    - gnome
    - zsh
    - ssh_keygen
    - bluetooth
    - git
    - docker
    - apps
    - browsers
